; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppID={{0624BFFD-56FE-42FD-AF8F-813C34138790}
AppName=Spolszczenie Thief 2X
AppVersion=Alfa1
;AppVerName=Spolszczenie Thief 2X 0.9 beta
AppPublisherURL=http://www.thief-portal.pl/
AppSupportURL=http://www.thief-portal.pl/
AppUpdatesURL=http://www.thief-portal.pl/
DefaultDirName={pf}\Thief 2\
DefaultGroupName=Spolszczenie Thief 2X
LicenseFile=E:\tlumacznia\t2x\do instalatora\licencja.txt
OutputDir=C:\Documents and Settings\Raven\Pulpit
OutputBaseFilename=Spolszczenie Thief 2X Wersja Testowa Alfa 1
SetupIconFile=E:\tlumacznia\t2x\do instalatora\t2xiconPL.ico
Compression=lzma2/Max
SolidCompression=true
InternalCompressLevel=Ultra

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"

[Files]
Source: "{app}\t2x\books\*.*"; DestDir: "{app}\t2x\backup\books"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\*.*"; DestDir: "{app}\t2x\backup\intrface"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\english\*.*"; DestDir: "{app}\t2x\backup\intrface\english"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss18\*.*"; DestDir: "{app}\t2x\backup\intrface\miss18"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss19\*.*"; DestDir: "{app}\t2x\backup\intrface\miss19"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss20\*.*"; DestDir: "{app}\t2x\backup\intrface\mis20"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss21\*.*"; DestDir: "{app}\t2x\backup\intrface\miss21"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss22\*.*"; DestDir: "{app}\t2x\backup\intrface\miss22"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss23\*.*"; DestDir: "{app}\t2x\backup\intrface\miss23"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss24\*.*"; DestDir: "{app}\t2x\backup\intrface\miss24"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss25\*.*"; DestDir: "{app}\t2x\backup\intrface\miss25"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss26\*.*"; DestDir: "{app}\t2x\backup\intrface\miss26"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss27\*.*"; DestDir: "{app}\t2x\backup\intrface\miss27"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss28\*.*"; DestDir: "{app}\t2x\backup\intrface\miss28"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss29\*.*"; DestDir: "{app}\t2x\backup\intrface\miss29"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\intrface\miss30\*.*"; DestDir: "{app}\t2x\backup\intrface\miss30"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "{app}\t2x\strings\*.*"; DestDir: "{app}\t2x\backup\strings"; Flags: external skipifsourcedoesntexist uninsneveruninstall
Source: "E:\tlumacznia\t2x\do instalatora\t2x\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:ProgramOnTheWeb,Spolszczenie Thief 2X}"; Filename: "http://www.thief-portal.pl/"
Name: "{group}\{cm:UninstallProgram,Spolszczenie Thief 2X}"; Filename: "{uninstallexe}"




[UninstallRun]
Filename: {app}\backup\backup.bat; Flags: WaitUntilIdle; 
